### ISSUE TITLE
Archivos faltantes

### ISSUE THREAD

**Issue by marcosgriselli** [argob/cuidar-ios#2]
Al intentar correr el projecto se encuentra un error de archivos faltantes en Escenas > Consejos. 

![faltante](https://user-images.githubusercontent.com/14804033/94341344-efd8b200-ffde-11ea-9520-847ecc5ce490.jpg)

<img width="273" alt="Screen Shot 2020-09-26 at 09 54 51" src="https://user-images.githubusercontent.com/14804033/94341350-054ddc00-ffdf-11ea-8721-c4f36fa97d40.png">

Si bien existe la referencia en el archivo `.pbxproj` de Xcode, los [archivos no se encuentran en el repositorio](https://github.com/argob/cuidar-ios/search?q=ConsejosViewController): 

<img width="1071" alt="Screen Shot 2020-09-26 at 09 55 29" src="https://user-images.githubusercontent.com/14804033/94341380-36c6a780-ffdf-11ea-90b2-2fc80f796363.png">

**Comment by marcosgriselli** [comment]
Lo mismo pasa con `CovidApp-Bridging-Header`. Si bien está agregado al `.gitignore` su referencia todavía existe entonces Xcode falla al compilar: 

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/14804033/94341506-324ebe80-ffe0-11ea-9ce9-02a46cef4f57.png">

**Comment by cuidarapp** [comment]
Efectivamente faltaban unos archivos, gracias por el aviso. Está corregido en el branch `pre-3.5.6-30-09-2020`, que en breve subiremos a master. Si no vas a usar NewRelic podés configurar el proyecto para que no use el Bridging Header, en el README está detallado.
Gracias!
